package zone.clanker.gort.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class GortColors(
    val background: Color,
    val surface: Color,
    val onSurface: Color,
    val border: Color,
    val shadow: Color,
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val accent: Color,
    val onAccent: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
) {
    companion object {
        fun light(
            background: Color = Color(0xFFF5F0E8),
            surface: Color = Color(0xFFFFFFFF),
            onSurface: Color = Color(0xFF1A1A1A),
            border: Color = Color(0xFF1A1A1A),
            shadow: Color = Color(0xFF1A1A1A),
            primary: Color = Color(0xFFFF5470),
            onPrimary: Color = Color(0xFFFFFFFF),
            primaryContainer: Color = Color(0xFFFFDADE),
            onPrimaryContainer: Color = Color(0xFF1A1A1A),
            secondary: Color = Color(0xFF36D399),
            onSecondary: Color = Color(0xFF1A1A1A),
            secondaryContainer: Color = Color(0xFFD0F5E5),
            onSecondaryContainer: Color = Color(0xFF1A1A1A),
            tertiary: Color = Color(0xFFFFBE0B),
            onTertiary: Color = Color(0xFF1A1A1A),
            tertiaryContainer: Color = Color(0xFFFFF3CC),
            onTertiaryContainer: Color = Color(0xFF1A1A1A),
            accent: Color = Color(0xFF4CC9F0),
            onAccent: Color = Color(0xFF1A1A1A),
            error: Color = Color(0xFFFF3333),
            onError: Color = Color(0xFFFFFFFF),
            errorContainer: Color = Color(0xFFFFD6D6),
            onErrorContainer: Color = Color(0xFF1A1A1A),
            success: Color = Color(0xFF36D399),
            onSuccess: Color = Color(0xFF1A1A1A),
            successContainer: Color = Color(0xFFD0F5E5),
            onSuccessContainer: Color = Color(0xFF1A1A1A),
            warning: Color = Color(0xFFFFBE0B),
            onWarning: Color = Color(0xFF1A1A1A),
            warningContainer: Color = Color(0xFFFFF3CC),
            onWarningContainer: Color = Color(0xFF1A1A1A),
        ) = GortColors(
            background, surface, onSurface, border, shadow,
            primary, onPrimary, primaryContainer, onPrimaryContainer,
            secondary, onSecondary, secondaryContainer, onSecondaryContainer,
            tertiary, onTertiary, tertiaryContainer, onTertiaryContainer,
            accent, onAccent,
            error, onError, errorContainer, onErrorContainer,
            success, onSuccess, successContainer, onSuccessContainer,
            warning, onWarning, warningContainer, onWarningContainer,
        )

        fun dark(
            background: Color = Color(0xFF1A1A1A),
            surface: Color = Color(0xFF2A2A2A),
            onSurface: Color = Color(0xFFF5F5F5),
            border: Color = Color(0xFFF5F5F5),
            shadow: Color = Color(0xFF000000),
            primary: Color = Color(0xFFFF5470),
            onPrimary: Color = Color(0xFFFFFFFF),
            primaryContainer: Color = Color(0xFF5C1A24),
            onPrimaryContainer: Color = Color(0xFFF5F5F5),
            secondary: Color = Color(0xFF36D399),
            onSecondary: Color = Color(0xFF1A1A1A),
            secondaryContainer: Color = Color(0xFF1A4D36),
            onSecondaryContainer: Color = Color(0xFFF5F5F5),
            tertiary: Color = Color(0xFFFFBE0B),
            onTertiary: Color = Color(0xFF1A1A1A),
            tertiaryContainer: Color = Color(0xFF4D3800),
            onTertiaryContainer: Color = Color(0xFFF5F5F5),
            accent: Color = Color(0xFF4CC9F0),
            onAccent: Color = Color(0xFF1A1A1A),
            error: Color = Color(0xFFFF3333),
            onError: Color = Color(0xFFFFFFFF),
            errorContainer: Color = Color(0xFF5C1A1A),
            onErrorContainer: Color = Color(0xFFF5F5F5),
            success: Color = Color(0xFF36D399),
            onSuccess: Color = Color(0xFF1A1A1A),
            successContainer: Color = Color(0xFF1A4D36),
            onSuccessContainer: Color = Color(0xFFF5F5F5),
            warning: Color = Color(0xFFFFBE0B),
            onWarning: Color = Color(0xFF1A1A1A),
            warningContainer: Color = Color(0xFF4D3800),
            onWarningContainer: Color = Color(0xFFF5F5F5),
        ) = GortColors(
            background, surface, onSurface, border, shadow,
            primary, onPrimary, primaryContainer, onPrimaryContainer,
            secondary, onSecondary, secondaryContainer, onSecondaryContainer,
            tertiary, onTertiary, tertiaryContainer, onTertiaryContainer,
            accent, onAccent,
            error, onError, errorContainer, onErrorContainer,
            success, onSuccess, successContainer, onSuccessContainer,
            warning, onWarning, warningContainer, onWarningContainer,
        )
    }
}

val LocalGortColors = staticCompositionLocalOf { GortColors.light() }
